//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string Codigo { get; set; }
        public int Vuelo { get; set; }
        public int Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
        public virtual Vuelo Vuelo1 { get; set; }
    }
}
